version: "3.5"

services:
  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: always

  backend:
    build: ./backend
    env_file:
      - ./envs/backend.env
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - /app/node_modules
      - ./backend:/app
    restart: always
  